#!/bin/bash
#
# it is assumed that the ELASTIC_IP env variable is set to the
# IP address of the amazon instance
#
echo "This script will configure a new EC2 Ubuntu instance with a"
echo "Xfce desktop and create a passwordless VNC server to connect to"
echo "It will also install docker and set up an SSH tunnel for"
echo "the local 5901 port to connect securily to the VNC server"
echo "..."
echo "step1: clearing out known_hosts"
sed -i '' "/${ELASTIC_IP}/d" ~/.ssh/known_hosts
#
echo "step2: configuring the EC2 instance for vnc and docker"
scp -i ~/.ssh/gcpEC2.pem ec2_xstartup ubuntu@$ELASTIC_IP:ec2_xstartup
ssh -i ~/.ssh/gcpEC2.pem ubuntu@$ELASTIC_IP 'bash -s' < ec2_desktop_setup.sh 
#
echo "step3: creating the tunnel for port 5901 (this will hang,"
echo "       so just kill it when you are done with the instance)"
#ec2tunnel 5901:5901
ssh ${EC2_USER}@${ELASTIC_IP} -L 5901/localhost/5901
